name: PR

on:
  pull_request: 

jobs:
  runner-job:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Test leetcode
      run: cd leetcode && go test -v -race ./...

    - name: Test skiena
      run: cd skiena && go test -v -race ./...
